---
name: Get Artifacts

on: 
  workflow_dispatch:
    inputs: {}

jobs:
  get-artifact:
    name: Get Artifacts
    runs-on: ubuntu-20.04
    env:
      _BRANCH: "main"
      _ARTIFACT_NAME: "build-artifact.zip"
    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Download build artifact
        uses: joseph-flinn/action-download-artifact@main
        with:
          workflow: build-artifact.yml
          workflow_conclusion: success
          branch: ${{ env._BRANCH }}
          name: ${{ env._ARTIFACT_NAME }}

      - name: Test previous step
        run: ls -atlh
