---
name: Get Artifact

on: 
  workflow_dispatch:
    inputs: {}

jobs:
  get-artifact:
    name: Get Artifact
    runs-on: ubuntu-20.04
    permissions:
      actions: read
    env:
      _BRANCH: "main"
      _ARTIFACT_NAME: "build-artifact.zip"
    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Get Download URL
        run: |
          #workflows=$(curl \
          #  -s -H "Accept: application/vnd.github.v3+json" \
          #  -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          #  https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs \
          #  | jq -c --arg branch_name "$_BRANCH" '.workflow_runs | map(select( .head_branch == "$branch_name" ))' 
          #)

          # Workflows
          curl \
            -s -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs > workflows.json
          cat workflows.json

          workflows=$(cat workflows.json | jq -c --arg branch_name "$_BRANCH" '.workflow_runs | map(select( .head_branch == "$branch_name" ))')
          latest_workflow=$(echo $workflows | jq 'max_by(.updated_at | strptime("%Y-%m-%dT%H:%M:%SZ")|mktime)')
          latest_artifacts_url=$(echo $latest_workflow | jq -r '.artifacts_url')
          echo $latest_artifacts_url

          #latest_artifacts=$(curl \
          #  -s -H "Accept: application/vnd.github.v3+json" \
          #  -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          #  $latest_artifacts_url | jq '.artifacts'
          #)
          
          # Latest Artifacts
          curl \
            -s -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            $latest_artifacts_url > latest_artifacts.json
          cat latest_artifacts.json
          latest_artifacts=$(cat latest_artifacts.json | jq '.artifacts'
          
          # Artifact Download URL
          artifact_download_url=$(
            echo $latest_artifacts \
              | jq -r --arg artifact_name "$_BUILD_ARTIFACT" '.[] | select( .name == "$artifact_name").archive_download_url'
          )
          echo $artifact_download_url

          # Get Artifact
          curl -LO $artifact_download_url

          ls -alth
